/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MinIoFileUrl } from '../../models/min-io-file-url';

export interface GetFileUrl$Params {
  bucketName: string;
  objectName: string;
}

export function getFileUrl(http: HttpClient, rootUrl: string, params: GetFileUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<MinIoFileUrl>> {
  const rb = new RequestBuilder(rootUrl, getFileUrl.PATH, 'get');
  if (params) {
    rb.path('bucketName', params.bucketName, {});
    rb.path('objectName', params.objectName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MinIoFileUrl>;
    })
  );
}

getFileUrl.PATH = '/files/{bucketName}/{objectName}';
