/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MinIoFileUrl } from '../../models/min-io-file-url';

export interface GetMyProfilePicture$Params {
}

export function getMyProfilePicture(http: HttpClient, rootUrl: string, params?: GetMyProfilePicture$Params, context?: HttpContext): Observable<StrictHttpResponse<MinIoFileUrl>> {
  const rb = new RequestBuilder(rootUrl, getMyProfilePicture.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MinIoFileUrl>;
    })
  );
}

getMyProfilePicture.PATH = '/files/pfp';
