/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileAnswer {
  correct?: boolean;
  createdDate?: string;
  extension: string;
  height?: number;
  id?: string;
  lastModifiedDate?: string;
  url?: string;
  width?: number;
}
