/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileOnTheQuestion {
  createdDate?: string;
  extension: string;
  height?: number;
  id?: string;
  lastModifiedDate?: string;
  sequencialOrder?: number;
  url?: string;
  width?: number;
}
