/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuestionText {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  sequencialOrder?: number;
  value: string;
}
