/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileAnswer } from '../models/file-answer';
import { FileOnTheQuestion } from '../models/file-on-the-question';
import { OpenQuestionAnswer } from '../models/open-question-answer';
import { QuestionText } from '../models/question-text';
import { Quiz } from '../models/quiz';
import { Tag } from '../models/tag';
import { TextAnswer } from '../models/text-answer';
import { User } from '../models/user';
export interface Question {
  answers?: Array<TextAnswer>;
  author?: User;
  createdDate?: string;
  done?: boolean;
  fileAnswers?: Array<FileAnswer>;
  files?: Array<FileOnTheQuestion>;
  id?: number;
  lastModifiedDate?: string;
  openQuestionAnswers?: Array<OpenQuestionAnswer>;
  public?: boolean;
  question: string;
  questionTexts?: Array<QuestionText>;
  quizzes?: Array<Quiz>;
  sequencialOrder?: number;
  tags: Array<Tag>;
}
