/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Question } from '../models/question';
import { Tag } from '../models/tag';
import { User } from '../models/user';
export interface Quiz {
  author: User;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  participants?: Array<User>;
  questions: Array<Question>;
  retryQuantity?: number;
  tags?: Array<Tag>;
  timeLimit: number;
}
