/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Question } from '../models/question';
import { Quiz } from '../models/quiz';
export interface Tag {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  name: string;
  questions?: Array<Question>;
  quizzes?: Array<Quiz>;
}
