/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TextAnswer {
  correct?: boolean;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  value?: string;
}
