/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileAnswer } from '../models/file-answer';
import { OpenQuestionAnswer } from '../models/open-question-answer';
import { Quiz } from '../models/quiz';
import { TextAnswer } from '../models/text-answer';
import { User } from '../models/user';
export interface UserAnswerToQuiz {
  createdDate?: string;
  fileAnswers?: Array<FileAnswer>;
  fileMistakes?: Array<FileAnswer>;
  id?: number;
  lastModifiedDate?: string;
  mistakes?: Array<TextAnswer>;
  openQuestionAnswers?: Array<OpenQuestionAnswer>;
  quiz?: Quiz;
  score?: number;
  user?: User;
  userAnswers?: Array<TextAnswer>;
}
