/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Quiz } from '../models/quiz';
import { UserAnswerToQuiz } from '../models/user-answer-to-quiz';
export interface User {
  email?: string;
  enabled?: boolean;
  first_name?: string;
  fullName?: string;
  id?: string;
  last_name?: string;
  participationList?: Array<Quiz>;
  realm_id?: string;
  userAnswerToQuizzes?: Array<UserAnswerToQuiz>;
  username?: string;
}
