/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { QuizControllerService } from './services/quiz-controller.service';
import { QuestionControllerService } from './services/question-controller.service';
import { MinIoComsService } from './services/min-io-coms.service';
import { AuthControllerService } from './services/auth-controller.service';
import { UserControllerService } from './services/user-controller.service';
import { TestesAuthenticadoService } from './services/testes-authenticado.service';
import { PingPongControllerService } from './services/ping-pong-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    QuizControllerService,
    QuestionControllerService,
    MinIoComsService,
    AuthControllerService,
    UserControllerService,
    TestesAuthenticadoService,
    PingPongControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
