/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { FileAnswer } from './models/file-answer';
export { FileOnTheQuestion } from './models/file-on-the-question';
export { LoginRequest } from './models/login-request';
export { MinIoFileNameAnswer } from './models/min-io-file-name-answer';
export { MinIoFileUrl } from './models/min-io-file-url';
export { OpenQuestionAnswer } from './models/open-question-answer';
export { Question } from './models/question';
export { QuestionText } from './models/question-text';
export { Quiz } from './models/quiz';
export { RegisterBuilder } from './models/register-builder';
export { Tag } from './models/tag';
export { TextAnswer } from './models/text-answer';
export { User } from './models/user';
export { UserAnswerToQuiz } from './models/user-answer-to-quiz';
