/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { QuizControllerService } from './services/quiz-controller.service';
export { QuestionControllerService } from './services/question-controller.service';
export { MinIoComsService } from './services/min-io-coms.service';
export { AuthControllerService } from './services/auth-controller.service';
export { UserControllerService } from './services/user-controller.service';
export { TestesAuthenticadoService } from './services/testes-authenticado.service';
export { PingPongControllerService } from './services/ping-pong-controller.service';
